esphome:
  name: esphome-web-c0b554

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source: # github://nielsnl68/esphome-components@main
      type: local
      path: C:\development\projects\esphome-components\components
    refresh: 10s


logger:
  level: verbose

display:
  - platform: graphics
    model: ili9341
    databus: spi
    clk_pin: 4
    miso_pin: 23
    dc_pin: 27
    cs_pin: 5
    reset_pin: 33

  - platform: graphics
    model: ILI9225
    databus: 8bit parallel
    dc_pin: 27
    cs_pin: 5
    wr_pin: 23
    d0_pin: 33
    d1_pin: 33
    d2_pin: 33
    d3_pin: 33
    d4_pin: 33
    d5_pin: 33
    d6_pin: 33
    d7_pin: 33

  - platform: graphics
    model: HX8369A
    databus: spi
    clk_pin: 4
    miso_pin: 23
    dc_pin: 27
    cs_pin: 5
    reset_pin: 33
    dimensions: 128x128
    rotation: 270


