esphome:
  name: esphome-web-c0b554

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source: # github://nielsnl68/esphome-components@main
      type: local
      path: C:\development\projects\esphome-components\components
    refresh: 10s

logger:
  level: verbose

display:
  platform: graphics
  model: ST7796
  databus: spi
  miso_pin: 12
  mosi_pin: 13
  clk_pin: 14
  cs_pin: 15
  dc_pin: 21
  reset_pin: 22
  backlight: tft_backlight
  rotation: 270
  lambda: |-
      it.setCursor(100,100);
      it.setTextColor(0xFFFF,0x0000);
      it.print("Hello World!");

color:
  - id: my_red
    red: 75%

font:
  - file: "gfonts://Roboto"
    id: my_font
    size: 20

# Example configuration entry
output:
  - platform: ledc
    pin: GPIO23
    id: gpio_backlight

# Example usage in a light
light:
  - platform: monochromatic
    output: gpio_backlight
    id: tft_backlight
    restore_mode: RESTORE_AND_ON 